### ISSUE TITLE
Policy and API Key UI

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego-ui#37]
Ego UI needs to be updated to include the new policy and API Key (token) endpoints. 

Policies are created to group permission sets together. 
Scopes are the individual permissions that a 
API keys ( called tokens) are a generated string that hold an individual users permissions. 

## References
**Swagger**: https://ego.qa.overture.bio/api/swagger-ui.html#/
**Wireframes**:  https://wiki.oicr.on.ca/display/DCCSOFT/Wireframes+for+Ego+Admin+UI
**Mockups**: 

## Frontend updates
- [ ] User Area
- [ ] Group Area
- [ ] Policy Area

## Backend updates
- [ ] Rename `Token Controller` to `API-Key Controller`
- [ ] Implement Refresh tokens
- [ ] Add ability to view Inherited Scopes
- [ ] Update Swagger
